version: "3.9"

networks:
  web:
    external: true
  internal:
    external: false
    driver: bridge

services:
  caddy:
    image: caddy:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web
      - internal

  db:
    image: postgres:14-alpine
    container_name: ysv-db
    env_file:
      - docker-compose.env
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432
    networks:
      - internal

  api:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    container_name: ysv-api
    env_file:
      - docker-compose.env
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      - internal
      - web

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    container_name: ysv-frontend
    env_file:
      - docker-compose.env
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - internal

volumes:
  caddy_data:
  caddy_config:
  postgres_data:


