"""add cart, cart_item table

Revision ID: 009cd2381394
Revises: 3816af4cdc13
Create Date: 2023-10-06 09:13:59.784826+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "009cd2381394"
down_revision: Union[str, None] = "3816af4cdc13"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_product_size_variant_id", "product_size_variant", ["id"]
    )
    op.create_table(
        "cart",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cart_item",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("cart_id", sa.UUID(), nullable=False),
        sa.Column("product_size_variant_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cart_id"],
            ["cart.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_size_variant_id"],
            ["product_size_variant.id"],
        ),
        sa.PrimaryKeyConstraint("id", "cart_id", "product_size_variant_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cart_item")
    op.drop_table("cart")
    # ### end Alembic commands ###
