"""add home collection fields

Revision ID: 21408cd238b4
Revises: b415e0e6bb9a
Create Date: 2023-10-08 06:57:51.716907+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "21408cd238b4"
down_revision: Union[str, None] = "b415e0e6bb9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collection", sa.Column("is_main_collection", sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE collection SET is_main_collection=false")
    op.alter_column("collection", "is_main_collection", nullable=False)
    op.add_column(
        "collection", sa.Column("is_show_in_home", sa.Boolean(), nullable=True)
    )
    op.execute("UPDATE collection SET is_show_in_home=false")
    op.alter_column("collection", "is_show_in_home", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("collection", "is_show_in_home")
    op.drop_column("collection", "is_main_collection")
    # ### end Alembic commands ###
