"""add storage of variant

Revision ID: ccb7db10ac9b
Revises: c35baf6c4342
Create Date: 2023-10-17 15:30:20.532429+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ccb7db10ac9b"
down_revision: Union[str, None] = "c35baf6c4342"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_size_variant", sa.Column("storage", sa.Integer(), nullable=True)
    )
    op.execute("UPDATE product_size_variant SET storage=1")
    op.alter_column("product_size_variant", "storage", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product_size_variant", "storage")
    # ### end Alembic commands ###
