"""add collection table

Revision ID: 61326d8774b9
Revises: 9a1395de6ba8
Create Date: 2023-09-29 13:15:56.688210+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "61326d8774b9"
down_revision: Union[str, None] = "9a1395de6ba8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("descriptions", sa.String(length=1000), nullable=False),
        sa.Column("preview_pic", sa.String(), nullable=False),
        sa.Column("is_on_sale", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("collection")
    # ### end Alembic commands ###
