"""add clothes_size table

Revision ID: b9a0c01c4a34
Revises: 61326d8774b9
Create Date: 2023-09-30 08:59:22.154571+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9a0c01c4a34'
down_revision: Union[str, None] = '61326d8774b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clothes_size',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clothes_size')
    # ### end Alembic commands ###
