"""add order, order_item table, add timestamp

Revision ID: db02424020ea
Revises: 009cd2381394
Create Date: 2023-10-06 18:36:47.767113+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "db02424020ea"
down_revision: Union[str, None] = "009cd2381394"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("fname", sa.String(), nullable=False),
        sa.Column("lname", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("street_address", sa.String(), nullable=False),
        sa.Column("zip_code", sa.String(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("cart_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order_item",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("product_size_variant_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_size_variant_id"],
            ["product_size_variant.id"],
        ),
        sa.PrimaryKeyConstraint("id", "order_id", "product_size_variant_id"),
    )
    op.add_column(
        "cart",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
    )
    op.add_column("cart", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column(
        "cart_item",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
    )
    op.add_column("cart_item", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column(
        "clothes_size",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
    )
    op.add_column("clothes_size", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column(
        "collection",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
    )
    op.add_column("collection", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column(
        "product",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
    )
    op.add_column("product", sa.Column("updated_at", sa.DateTime(), nullable=True))
    op.add_column(
        "product_picture",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
    )
    op.add_column(
        "product_picture", sa.Column("updated_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "product_size_variant",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
    )
    op.add_column(
        "product_size_variant", sa.Column("updated_at", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "user",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
    )
    op.add_column("user", sa.Column("updated_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    op.drop_column("product_size_variant", "updated_at")
    op.drop_column("product_size_variant", "created_at")
    op.drop_column("product_picture", "updated_at")
    op.drop_column("product_picture", "created_at")
    op.drop_column("product", "updated_at")
    op.drop_column("product", "created_at")
    op.drop_column("collection", "updated_at")
    op.drop_column("collection", "created_at")
    op.drop_column("clothes_size", "updated_at")
    op.drop_column("clothes_size", "created_at")
    op.drop_column("cart_item", "updated_at")
    op.drop_column("cart_item", "created_at")
    op.drop_column("cart", "updated_at")
    op.drop_column("cart", "created_at")
    op.drop_table("order_item")
    op.drop_table("order")
    # ### end Alembic commands ###
