"""remove cart_id col, add is_paid col of order

Revision ID: 744ec9c5ba9f
Revises: db02424020ea
Create Date: 2023-10-06 18:57:35.534687+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "744ec9c5ba9f"
down_revision: Union[str, None] = "db02424020ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order", sa.Column("is_paid", sa.Boolean(), nullable=False))
    op.add_column("order", sa.Column("is_delivered", sa.Boolean(), nullable=False))
    op.drop_column("order", "cart_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order", sa.Column("cart_id", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_column("order", "is_paid")
    op.drop_column("order", "is_delivered")
    # ### end Alembic commands ###
