"""split description fields

Revision ID: cd36fe9e223c
Revises: 2b7f3c39efe9
Create Date: 2023-10-10 03:55:40.232061+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cd36fe9e223c"
down_revision: Union[str, None] = "2b7f3c39efe9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collection",
        sa.Column("main_collection_description_2", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("collection", "main_collection_description_2")
    # ### end Alembic commands ###
