"""add layout table

Revision ID: 7d56714cadf1
Revises: cd36fe9e223c
Create Date: 2023-10-11 12:45:57.098070+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7d56714cadf1"
down_revision: Union[str, None] = "cd36fe9e223c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collection",
        sa.Column("lookbook_layout_code", sa.String(), nullable=True, default="two"),
    )
    op.execute("UPDATE collection SET lookbook_layout_code='two'")
    op.alter_column("collection", "lookbook_layout_code", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("collection", "lookbook_layout_code")
    # ### end Alembic commands ###
