"""add cart_id col of order

Revision ID: b415e0e6bb9a
Revises: 744ec9c5ba9f
Create Date: 2023-10-06 20:29:52.922795+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b415e0e6bb9a"
down_revision: Union[str, None] = "744ec9c5ba9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("order", sa.Column("cart_id", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order", "cart_id")
    # ### end Alembic commands ###
