"""add product_size_variant table

Revision ID: 26cb0c91ce56
Revises: b8df361f9391
Create Date: 2023-10-02 17:05:54.289138+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "26cb0c91ce56"
down_revision: Union[str, None] = "b8df361f9391"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_size_variant",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("product_id", sa.UUID(), nullable=False),
        sa.Column("clothes_size_id", sa.UUID(), nullable=False),
        sa.Column("is_pre_order", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["clothes_size_id"],
            ["clothes_size.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id", "product_id", "clothes_size_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_size_variant")
    # ### end Alembic commands ###
