"""add main collection fields

Revision ID: 2b7f3c39efe9
Revises: 21408cd238b4
Create Date: 2023-10-08 19:11:07.654311+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2b7f3c39efe9"
down_revision: Union[str, None] = "21408cd238b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "collection",
        sa.Column("main_collection_description", sa.String(), nullable=True),
    )
    op.add_column(
        "collection", sa.Column("main_collection_pics", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("collection", "main_collection_pics")
    op.drop_column("collection", "main_collection_description")
    # ### end Alembic commands ###
