"""add collection home_position

Revision ID: ee3706496e3e
Revises: ccb7db10ac9b
Create Date: 2023-10-20 10:02:52.630593+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ee3706496e3e"
down_revision: Union[str, None] = "ccb7db10ac9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("collection", sa.Column("home_position", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("collection", "home_position")
    # ### end Alembic commands ###
